app.environment: production

server:
  port: 8761
  servlet.context-path: /discovery

management:
  endpoints:
    web:
      base-path: /manage
  server:
    port: 8081
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always


eureka:
  environment: ${app.environment}
  datacenter: DIFI-MOVE
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl.defaultZone: http://localhost:${server.port}${server.servlet.context-path}/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri:  git@github.com:difi/move-config.git
          search-paths: config
#          clone-on-start: true
          force-pull: true
          basedir: /config_cache
        health:
          repositories:
            integrasjonspunkt:
              name: integrasjonspunkt
              profiles: ${app.environment:default}
            serviceregistry:
              name: serviceregistry
              profiles: ${app.environment:default}
        prefix: /config
  application:
    name: "@project.name@"

info.app:
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"


#security.oauth2.resource.token-info-uri=https://eid-exttest.difi.no/idporten-oidc-provider/tokeninfo
#security.oauth2.resource.user-info-uri=${security.oauth2.resource.token-info-uri}
#security.oauth2.resource.id=configserver